Description: >
    Igor J.L Ndiramiye / Udacity Project 2
    CloudFormation template for s3 bucket 

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resources
        Type: String
    
Resources:
    S3Bucket:
        Type: AWS::S3::Bucket
        Description: Creating Amazon S3 bucket from CloudFormation
        Properties:
            BucketName: !Sub ${EnvironmentName}-s3-bucket
Outputs:
    S3Bucket:
        Description: Bucket Created using this template.
        Value: !Ref S3Bucket